### ISSUE TITLE
Adding option to set layout

### ISSUE THREAD

**Issue by adisen99** [ojroques/nvim-lspfuzzy#13]
The option to set fzf_layout is missing. Unable to use `fzf_layout = { 'down' : '30%' }` to get the fzf window down rather than in the middle.

Is it there and I am missing something?

If not, please add that support.

My configuration is - 

```lua
-- Lsp fuzzy seach setup

local g = vim.g
local map = vim.api.nvim_set_keymap

require('lspfuzzy').setup {
  methods = 'all',         -- either 'all' or a list of LSP methods (see below)
  fzf_layout = 'down:30%',
  fzf_preview = {          -- arguments to the FZF '--preview-window' option
    'right:+{2}-/2'          -- preview on the right and centered on entry
  },
  fzf_action = {           -- FZF actions
    ['ctrl-t'] = 'tabedit',  -- go to location in a new tab
    ['ctrl-v'] = 'vsplit',   -- go to location in a vertical split
    ['ctrl-x'] = 'split',    -- go to location in a horizontal split
  },
  fzf_modifier = ':~:.',   -- format FZF entries, see |filename-modifiers|
  fzf_trim = true,         -- trim FZF entries
}

map('n', '<A-g>', ':GFiles<cr>', {})
map('n', '<A-p>', ':Files<cr>', {})
```

I have added the option for layout as down but still the window is coming as floating window in the center.

**Comment by ojroques** [comment]
Hello !

As mentioned in the [README.md](https://github.com/ojroques/nvim-lspfuzzy/blob/main/README.md#configuration), the plugin will respect your FZF config. So just put `let g:fzf_layout = {'down': '30%'}` in your .vimrc or `g['fzf_layout'] = {down = '30%'}` in Lua and you should be good.

For the `fzf_action` and `fzf_preview` options I'm not using the default values of FZF that's why they can be configured in the plugin, but for the others the plugin will follow either your own FZF settings or the FZF default.

Feel free to re-open this if you have further issues.
