### ISSUE TITLE
Reopen the last results

### ISSUE THREAD

**Issue by willir** [ojroques/nvim-lspfuzzy#24]
Is it possible to reopen the window with the last command results?
E.g. If I do _find usages_, and go to the first usage, I might want to go to another usage, after I reviewed the first one. Would it be possible to save the results and have an option to reopen the window?

Or another way to implement something like that would be to duplicate results into the QuickFix window; so you can run `copen` and look at them later.

BTW, thanks for the great plugin.

**Comment by ojroques** [comment]
Hello!

That was a good idea, I've implemented it in the latest commit with a new command `LspFuzzyLast`. I prefer to keep the quickfix window for multi-selection so the last results also use the FZF window.

Note that you need to set `save_last` to `true` in the plugin configuration for the command to work. This is because I didn't want to introduce memory and speed overhead when the results are thousands lines long.
