### ISSUE TITLE
Is able to support fuzzy finding of workspace symbols ?

### ISSUE THREAD

**Issue by zanglg** [ojroques/nvim-lspfuzzy#3]
List all the workspace symbols, and searching on the fly.

**Comment by ojroques** [comment]
Yes it should support it, see [Supported LSP methods](https://github.com/ojroques/nvim-lspfuzzy#supported-lsp-methods).

If nothing appears it may be your LSP server that does not support that method. Let me know if it does support them but the plugin still does not display anything.

**Comment by zanglg** [comment]
I'm using clangd with nvim-lsp, I notice clangd support workspace/symbol, but I can only search with a concrete symbol。
calling vim.lsp.buf.workspace_symbol() give me a pattern to type, not listing all the symbols.

**Comment by ojroques** [comment]
But when you make a query the results are displayed in fzf right?

I think it is because how neovim lsp workspace symbol query works, see  https://github.com/neovim/neovim/blob/b6723e1ea065a818e6cda4c917c9c11d7cb67652/runtime/doc/lsp.txt#L1031 :
- when you call workspace_symbol without argument neovim ask you for a string to query
- then it makes the request using the workspace symbol method
- the plugin displays the results of that request in fzf

Unfortunately you cannot make a workspace symbol without argument. So there's not really a way to filter *all* symbols through fzf.

**Comment by zanglg** [comment]
That's it. It is really not a nvim-lspfuzzy issue. closed. thanks again.
