### ISSUE TITLE
Why is codeaction not supported?

### ISSUE THREAD

**Issue by ycycyyc** [ojroques/nvim-lspfuzzy#35]
This plugin is very good, but it doesn't seem to support codeaction.

**Comment by ojroques** [comment]
Because unlike other LSP methods, we cannot redefine the handler for code actions: see [here](https://github.com/neovim/neovim/blob/b25abbf4b8a08899bba87809124c882928d99e21/runtime/lua/vim/lsp/buf.lua#L698-L707). There exists workarounds but I don't want to implement them into the plugin, it would complexify things too much. Check [this plugin](https://github.com/gfanto/fzf-lsp.nvim) if you really want support for code actions.

Also I don't really see the point of fuzzy searching code actions anyway. I found it faster to select an action by typing its number in the default quickfix window than via FZF, because you don't really know which action is the one you want before reading all results.

**Comment by ycycyyc** [comment]
Thanks for the quick reply!
