### ISSUE TITLE
Maintain the fzf_preview_window options.

### ISSUE THREAD

**Issue by lucax88x** [ojroques/nvim-lspfuzzy#6]
I have defaulted fzf to show preview in the bottom ('down') but it keeps showing on right, so I think that you are probably overriding this settings somehow.

**Comment by ojroques** [comment]
You can use `g:fzf_preview_window` now. I recommend that you append `+{2}-/2` to your option though or else the preview may not display the correct line. In your case `let g:fzf_preview_window = ['down:+{2}-/2']`.

If appending that string causes issues elsewhere I can update the plugin so that it appends it internally. So please re-open this issue if it's not working correctly.

**Comment by lucax88x** [comment]
I did not need to append this piece of string, it works perfectly. Thanks!
